#!/usr/bin/env bash

set -e

envfile="/etc/dworm.d/.service-env"
exampleenvfile="/etc/dworm.d/.env.example"

if [[ ! -f $envfile ]]; then
  cp $exampleenvfile $envfile
fi

systemctl enable dworm &>/dev/null
systemctl start dworm &>/dev/null
